SIM            = icarus
TOPLEVEL_LANG  = verilog
TOPLEVEL       = conv2d_accel
COCOTB_TEST_MODULES = test_conv2d_accel
VERILOG_SOURCES = $(PWD)/hdl/conv2d_accel.sv

include $(shell cocotb-config --makefiles)/Makefile.sim
