SIM            = icarus
TOPLEVEL_LANG  = verilog
VERILOG_SOURCES = $(PWD)/mac_correct.sv
TOPLEVEL       = mac
MODULE         = test_mac

include $(shell cocotb-config --makefiles)/Makefile.sim
